name: System Configurations Helpers
description: Drible // Marketing Digital & Branding
footer-links:
  email: tiago.silva@drible.pt
  facebook: agenciadrible
  github: popperz0r/sys-config
  twitter: popperz0r
url: https://popperz0r.github.io/sys-config/
baseurl: "/sys-config"
theme: jekyll-theme-cayman
